# Generated by Django 5.1.6 on 2025-03-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_data',
        ),
    ]
